import type { CollectibleCard, CouponReward, CardSet } from "../types/gacha";

// ── 🎴 COLLECTIBLE FOOD & CHEF CARDS ──
export const GACHA_CARDS: CollectibleCard[] = [
  // ── 6★ UR (Prism Rainbow / Divine) ──
  {
    id: "card_ur_uncle_get",
    name: "ลุงเกตุ เทพเจ้ากระทะเหล็ก",
    nameEn: "God Chef Lung Get",
    title: "ปรมาจารย์เพลิงวิญญาณแห่งสะพานปลา",
    rarity: 6,
    category: "character",
    image: "/logoHome.png",
    flavorPower: 99999,
    secretBuff: "ออร่าผัดกระทะทองคำ: กลิ่นหอมสะท้านโลกา",
    lore: "ด้วยตะหลิวคู่ใจและกระทะเหล็กที่ผ่านเปลวเพลิงมากว่า 40 ปี ประกายไฟสะท้อนควันหอมกรุ่นที่ปลุกความหิวโหยได้ทุกภพภูมิ",
    flavorTags: ["ตำนาน", "เทพกระทะ", "กลิ่นควันไหม้", "ลับเฉพาะ"],
    setId: "set_legend_lung_get",
  },
  {
    id: "card_ur_golden_moo_grob",
    name: "หมูกรอบเพลิงสวรรค์",
    nameEn: "Heavenly Crispy Pork",
    title: "ความกรอบ 9 มิติระดับจักรวาล",
    rarity: 6,
    category: "signature",
    image: "/meal/krapao.jpg",
    flavorPower: 88888,
    secretBuff: "เสียงเคี้ยวกรุบกรอบก้องกังวานในหัวใจ",
    lore: "หมูสามชั้นที่ผ่านการต้ม ทอด และเป่าลมร้อนด้วยเคล็ดวิชาลับ หนังกรอบฟูเนื้อฉ่ำนุ่มกระทั่งเหล่าทวยเทพยังต้องต่อคิวรอชิม",
    flavorTags: ["กรอบฟู", "สามชั้นทองคำ", "ชุ่มฉ่ำ", "ไร้เทียมทาน"],
    setId: "set_legend_lung_get",
  },

  // ── 5★ SSR (Gold / Legendary) ──
  {
    id: "card_ssr_krapao_king",
    name: "ราชากะเพราหมูสับ",
    nameEn: "King of Krapao",
    title: "ความเผ็ดร้อนสะท้านปฐพี",
    rarity: 5,
    category: "signature",
    image: "/meal/krapao.jpg",
    flavorPower: 45000,
    secretBuff: "รสชาติเข้มข้นจัดจ้านติดปลายลิ้น",
    lore: "ใบกะเพราป่าแท้ ผัดคั่วแห้งไร้น้ำมันเยิ้ม คลุกเคล้าพริกขี้หนูสวนตำสด เสิร์ฟร้อนควันพวยพุ่ง",
    flavorTags: ["เผ็ดร้อน", "กะเพราป่า", "คั่วแห้ง", "Signature"],
    setId: "set_wok_master",
  },
  {
    id: "card_ssr_lava_egg",
    name: "ไข่ดาวกรอบลาวาเยิ้ม",
    nameEn: "Golden Lava Crispy Egg",
    title: "ไข่แดงเยิ้มทองคำ ขอบกรอบฟูทะลุฟ้า",
    rarity: 5,
    category: "topping",
    image: "/meal/krapao.jpg",
    flavorPower: 42000,
    secretBuff: "ราดน้ำปลาพริกเพิ่มความอร่อย 300%",
    lore: "ไข่เป็ดสดจากฟาร์ม ทอดในน้ำมันร้อนจัดด้วยจังหวะมือที่แม่นยำ ไข่ขาวฟูกรอบสะใจแต่ไข่แดงยังเป็นลาวาเนียนนุ่มเยิ้ม",
    flavorTags: ["ไข่แดงเยิ้ม", "ขอบกรอบ", "ท็อปปิ้งเทพ", "เข้ากันทุกจาน"],
    setId: "set_crispy_egg_combo",
  },
  {
    id: "card_ssr_pad_tua_sea",
    name: "ผัดพริกแกงทะเลเดือด",
    nameEn: "Boiling Sea Chili Curry",
    title: "มหาสมุทรแห่งเครื่องแกงสด",
    rarity: 5,
    category: "signature",
    image: "/meal/pad_tua_sea.jpg",
    flavorPower: 44000,
    secretBuff: "กลิ่นหอมสมุนไพรสดทะลวงลมปราณ",
    lore: "กุ้งและหมึกสดจากเรือประมง คลุกเคล้าพริกแกงใต้สูตรต้นตำรับ กลิ่นใบมะกรูดและพริกชี้ฟ้าหอมระเบิดทั่วร้าน",
    flavorTags: ["ซีฟู้ดสด", "พริกแกงใต้", "เผ็ดเข้มข้น", "ทะเลเดือด"],
    setId: "set_wok_master",
  },

  // ── 4★ SR (Purple / Rare & Special) ──
  {
    id: "card_sr_pad_see_ew",
    name: "ผัดซีอิ๊วหอมควันกระทะ",
    nameEn: "Wok Hei Pad See Ew",
    title: "เส้นใหญ่นุ่มเหนียว กลิ่นกระทะไหม้พอดี",
    rarity: 4,
    category: "wok",
    image: "/meal/pad_see_ew.jpg",
    flavorPower: 24000,
    secretBuff: "ความนุ่มละมุนลิ้นระดับพรีเมียม",
    lore: "คะน้ากรอบสด เส้นใหญ่เคลือบซีอิ๊วดำสูตรหมักโบราณ ผัดด้วยไฟแรงจัดจนได้กลิ่นหอมกระทะที่เป็นเอกลักษณ์",
    flavorTags: ["หอมควันกระทะ", "เส้นเหนียวนุ่ม", "คะน้ากรอบ", "คลาสสิก"],
    setId: "set_wok_master",
  },
  {
    id: "card_sr_fried_rice",
    name: "ข้าวผัดกระเทียมไฟลุก",
    nameEn: "Blazing Garlic Fried Rice",
    title: "เม็ดข้าวร่วนหอม มันวาวทุกเม็ด",
    rarity: 4,
    category: "wok",
    image: "/meal/fried_rice.jpg",
    flavorPower: 22000,
    secretBuff: "หอมกระเทียมเจียวทองคำฟุ้งติดจมูก",
    lore: "ข้าวหอมมะลิเก่าแช่เย็น ผัดด้วยกระเทียมเจียวสีเหลืองทองและไข่ไก่จนเคลือบทุกเม็ดข้าว สวยงามและหอมฟุ้ง",
    flavorTags: ["ข้าวร่วนสวย", "กระเทียมเจียว", "หอมละมุน", "จานโปรด"],
    setId: "set_crispy_egg_combo",
  },
  {
    id: "card_sr_pad_pong_gari",
    name: "ผัดผงกะหรี่นุ่มละมุน",
    nameEn: "Silk Golden Curry",
    title: "ไข่นุ่มครีมมี่ กลิ่นเครื่องเทศหอมมัน",
    rarity: 4,
    category: "wok",
    image: "/meal/pad_pong_gari.jpg",
    flavorPower: 21500,
    secretBuff: "ละลายในปากฟินทุกคำ",
    lore: "ผัดผงกะหรี่เคลือบเนื้อหมูจนฉ่ำวาว รสชาติกลมกล่อม หวานมันเค็มลงตัว ทานกับข้าวสวยร้อนๆ คือที่สุด",
    flavorTags: ["ครีมมี่", "หอมผงกะหรี่", "ไข่นุ่ม", "กลมกล่อม"],
    setId: "set_wok_master",
  },
  {
    id: "card_sr_frost_longan",
    name: "น้ำลำไยเกล็ดหิมะ",
    nameEn: "Frost Longan Nectar",
    title: "เนื้อลำไยตู้มๆ หวานฉ่ำดับร้อน",
    rarity: 4,
    category: "drink",
    image: "/meal/longan_juice.jpg",
    flavorPower: 19000,
    secretBuff: "สดชื่นดับเผ็ดทันที 100%",
    lore: "ต้มจากเนื้อลำไยสีทองธรรมชาติ หอมหวานละมุน เสิร์ฟพร้อมน้ำแข็งเกล็ดเย็นชื่นใจ ดับความเผ็ดร้อนได้ชะงัด",
    flavorTags: ["เนื้อลำไยแน่น", "หวานชื่นใจ", "ดับกระหาย", "เครื่องดื่ม"],
    setId: "set_crispy_egg_combo",
  },

  // ── 3★ R (Blue / Common Goodies) ──
  {
    id: "card_r_jasmine_rice",
    name: "ข้าวหอมมะลิคัดพิเศษ",
    nameEn: "Aromatic Jasmine Rice",
    title: "ข้าวสวยร้อนๆ นุ่มเรียวยาว",
    rarity: 3,
    category: "topping",
    image: "/meal/khao_moo_garlic.jpg",
    flavorPower: 8500,
    secretBuff: "ฐานรากแห่งความอร่อยของทุกมื้อ",
    lore: "ข้าวหอมมะลิแท้จากทุ่งกุลาร้องไห้ หุงขึ้นหม้อ เม็ดเรียงสวย นุ่มหอมกรุ่นทุกจาน",
    flavorTags: ["หอมมะลิแท้", "ข้าวสวยร้อนๆ", "นุ่มละมุน"],
    setId: "set_crispy_egg_combo",
  },
  {
    id: "card_r_secret_sauce",
    name: "พริกน้ำปลาสูตรลับ",
    nameEn: "Secret Chili Fish Sauce",
    title: "เครื่องปรุงชูรสชาติในตำนาน",
    rarity: 3,
    category: "topping",
    image: "/meal/pad_pak.jpg",
    flavorPower: 9200,
    secretBuff: "เพิ่มมิติรสชาติเผ็ดเปรี้ยวเค็ม",
    lore: "น้ำปลาแท้ชั้นดี บีบมะนาวสด พริกขี้หนูซอยและกระเทียมฝานบาง ราดจานไหนก็หยุดกินไม่ได้",
    flavorTags: ["มะนาวสด", "พริกกระเทียม", "รสจัดจ้าน"],
    setId: "set_crispy_egg_combo",
  },
  {
    id: "card_r_chilled_water",
    name: "น้ำเปล่าเย็นฉ่ำ",
    nameEn: "Chilled Mountain Water",
    title: "น้ำดื่มเย็นสดชื่นบริสุทธิ์",
    rarity: 3,
    category: "drink",
    image: "/meal/water.jpg",
    flavorPower: 5000,
    secretBuff: "คืนความสดชื่น 100%",
    lore: "น้ำดื่มสะอาดบริสุทธิ์ แช่เย็นเจี๊ยบ ดับกระหายคลายเผ็ดได้ดีเยี่ยมในทุกช่วงเวลา",
    flavorTags: ["เย็นชื่นใจ", "บริสุทธิ์", "ดับกระหาย"],
    setId: "set_crispy_egg_combo",
  },
  {
    id: "card_r_coke",
    name: "โค้กเย็นซ่า",
    nameEn: "Chilled Cola",
    title: "ความซ่าสดชื่นคู่โต๊ะอาหาร",
    rarity: 3,
    category: "drink",
    image: "/meal/coke.jpg",
    flavorPower: 6500,
    secretBuff: "ความซ่าสดชื่นดับเลี่ยน",
    lore: "เครื่องดื่มน้ำอัดลมเย็นจัด ซ่าถึงใจ เติมเต็มความสุขในทุกมื้ออาหาร",
    flavorTags: ["ซ่าสดชื่น", "เย็นจัด", "คู่หูมื้ออร่อย"],
    setId: "set_crispy_egg_combo",
  },
];

// ── 🎁 LUCKY COUPONS & REWARDS ──
export const GACHA_COUPONS: CouponReward[] = [
  // ── 5★ SSR (Gold / Massive Perks) ──
  {
    id: "coupon_ssr_50pct",
    name: "คูปองส่วนลด 50% มหาเฮง",
    nameEn: "50% Mega Lucky Discount",
    description: "ลดทันที 50% (ลดสูงสุด 100 บาท)",
    descriptionEn: "50% off (Max discount ฿100)",
    rarity: 5,
    type: "discount_percent",
    discountPercent: 50,
    code: "LUNGGET50",
    image: "/meal/krapao.jpg",
  },
  {
    id: "coupon_ssr_free_krapao",
    name: "ฟรี! ข้าวกะเพราหมูสับ 1 จาน",
    nameEn: "Free Krapao Pork Dish",
    description: "รับฟรีข้าวกะเพราหมูสับยอดฮิตมูลค่า 60 บาท",
    descriptionEn: "Free signature pork basil rice dish (Valued ฿60)",
    rarity: 5,
    type: "discount_fixed",
    discountAmount: 60,
    freeDishName: "กระเพราหมูสับ (ข้าวราด)",
    code: "FREEKRAPAO",
    image: "/meal/krapao.jpg",
  },
  {
    id: "coupon_ssr_off_50",
    name: "คูปองเงินสด 50 บาท",
    nameEn: "฿50 Cash Coupon",
    description: "ลดทันที 50 บาท (เมื่อสั่งซื้อขั้นต่ำ 100 บาท)",
    descriptionEn: "฿50 instant cash off on min spend ฿100",
    rarity: 5,
    type: "discount_fixed",
    discountAmount: 50,
    minSpend: 100,
    code: "LUCK50BAHT",
    image: "/meal/pad_see_ew.jpg",
  },

  // ── 4★ SR (Purple / Great Perks) ──
  {
    id: "coupon_sr_free_egg",
    name: "ฟรี! ไข่ดาวกรอบฟองโต",
    nameEn: "Free Crispy Lava Egg",
    description: "รับฟรีท็อปปิ้งไข่ดาวลาวากรอบ 1 ฟอง มูลค่า 10 บาท",
    descriptionEn: "Free crispy fried egg addon",
    rarity: 4,
    type: "discount_fixed",
    discountAmount: 10,
    freeAddonName: "ไข่ดาว",
    code: "FREEEGGLAVA",
    image: "/meal/krapao.jpg",
  },
  {
    id: "coupon_sr_free_delivery",
    name: "คูปองส่งฟรี 40 บาท",
    nameEn: "Free Delivery ฿40",
    description: "ฟรีค่าจัดส่ง Delivery สูงสุด 40 บาท",
    descriptionEn: "Free delivery fee up to ฿40",
    rarity: 4,
    type: "discount_fixed",
    discountAmount: 40,
    code: "FREEDELIVERY",
    image: "/meal/pad_tua_sea.jpg",
  },
  {
    id: "coupon_sr_20pct",
    name: "คูปองส่วนลด 20%",
    nameEn: "20% Discount Coupon",
    description: "ลดทันที 20% (สั่งซื้อขั้นต่ำ 80 บาท)",
    descriptionEn: "20% off on minimum spend ฿80",
    rarity: 4,
    type: "discount_percent",
    discountPercent: 20,
    minSpend: 80,
    code: "SUPER20",
    image: "/meal/fried_rice.jpg",
  },
  {
    id: "coupon_sr_free_longan",
    name: "ฟรี! น้ำลำไยเย็นชื่นใจ",
    nameEn: "Free Longan Drink",
    description: "รับฟรีน้ำลำไยเกล็ดหิมะ 1 แก้ว มูลค่า 45 บาท",
    descriptionEn: "Free sweet iced longan drink (Valued ฿45)",
    rarity: 4,
    type: "discount_fixed",
    discountAmount: 45,
    freeDishName: "น้ำลำไย",
    code: "FREELONGAN",
    image: "/meal/longan_juice.jpg",
  },

  // ── 3★ R (Blue / Everyday Perks) ──
  {
    id: "coupon_r_10baht",
    name: "คูปองลด 10 บาท",
    nameEn: "฿10 Discount Voucher",
    description: "ลดทันที 10 บาท ไม่มีขั้นต่ำ",
    descriptionEn: "฿10 discount without min spend",
    rarity: 3,
    type: "discount_fixed",
    discountAmount: 10,
    code: "SAVE10",
    image: "/meal/pad_pak.jpg",
  },
  {
    id: "coupon_r_5baht",
    name: "คูปองลด 5 บาท",
    nameEn: "฿5 Discount Voucher",
    description: "ลดทันที 5 บาท ไม่มีขั้นต่ำ",
    descriptionEn: "฿5 discount without min spend",
    rarity: 3,
    type: "discount_fixed",
    discountAmount: 5,
    code: "SAVE5",
    image: "/meal/water.jpg",
  },
  {
    id: "coupon_r_extra_rice",
    name: "คูปองเพิ่มข้าวฟรี",
    nameEn: "Free Extra Rice Voucher",
    description: "ลด 10 บาทสำหรับสั่งข้าวสวยหรืออิ่มจุใจ",
    descriptionEn: "฿10 off for rice topping",
    rarity: 3,
    type: "discount_fixed",
    discountAmount: 10,
    code: "EXTRARICE",
    image: "/meal/khao_moo_garlic.jpg",
  },
];

// ── 🏆 CARD SETS & COMPLETION REWARDS ──
export const GACHA_SETS: CardSet[] = [
  {
    id: "set_legend_lung_get",
    name: "เซ็ตตำนานลุงเกตุ (Legend of Lung Get)",
    nameEn: "Legend of Lung Get Set",
    description: "สะสมการ์ดระดับ UR ทั้ง 2 ใบ: ลุงเกตุ เทพกระทะเหล็ก และ หมูกรอบเพลิงสวรรค์",
    requiredCardIds: ["card_ur_uncle_get", "card_ur_golden_moo_grob"],
    rewardDescription: "รับสถานะ VIP Gold Badge + ตั๋วสุ่มฟรี 20 ใบ + คูปองลด 50%",
    rewardType: "coupon",
    rewardCoupon: {
      id: "coupon_set_legend_master",
      name: "คูปองเซ็ตตำนานลุงเกตุ 50%",
      nameEn: "Master Legend 50% Off",
      description: "ลดทันที 50% พิเศษเฉพาะผู้สะสมเซ็ตตำนานครบ",
      descriptionEn: "50% off for Master Legend collectors",
      rarity: 6,
      type: "discount_percent",
      discountPercent: 50,
      code: "LEGENDMASTER50",
      image: "/logoHome.png",
    },
    rewardTickets: 20,
    badgeTitle: "👑 จอมทัพกระทะทองคำลุงเกตุ",
  },
  {
    id: "set_wok_master",
    name: "เซ็ตปรมาจารย์กระทะเหล็ก (Wok Masters)",
    nameEn: "Wok Masters Set",
    description: "สะสมการ์ดเมนูผัดกระทะไฟแรง: ราชากะเพรา, ผัดพริกแกงทะเล, ผัดซีอิ๊ว, ผัดผงกะหรี่",
    requiredCardIds: [
      "card_ssr_krapao_king",
      "card_ssr_pad_tua_sea",
      "card_sr_pad_see_ew",
      "card_sr_pad_pong_gari",
    ],
    rewardDescription: "รับตั๋วสุ่มฟรี 10 ใบ + คูปองฟรีข้าวกะเพราหมูสับ 1 จาน",
    rewardType: "ticket",
    rewardTickets: 10,
    rewardCoupon: {
      id: "coupon_set_wok_free_dish",
      name: "ฟรี! กะเพราหมูสับ (รางวัลเซ็ต Wok Master)",
      nameEn: "Free Krapao Pork (Wok Master Reward)",
      description: "รับฟรีข้าวกะเพราหมูสับ 1 จานทันที",
      descriptionEn: "Free Krapao pork dish reward",
      rarity: 5,
      type: "discount_fixed",
      discountAmount: 60,
      code: "WOKMASTERFREE",
      image: "/meal/krapao.jpg",
    },
    badgeTitle: "🔥 เซียนกระทะไฟลุก",
  },
  {
    id: "set_crispy_egg_combo",
    name: "เซ็ตคู่หูจานอร่อย & เครื่องดื่มสดชื่น",
    nameEn: "Delicious Meal & Drink Combo Set",
    description: "สะสมการ์ด: ไข่ดาวลาวา, ข้าวผัดกระเทียม, น้ำลำไย, ข้าวหอมมะลิ, พริกน้ำปลา",
    requiredCardIds: [
      "card_ssr_lava_egg",
      "card_sr_fried_rice",
      "card_sr_frost_longan",
      "card_r_jasmine_rice",
      "card_r_secret_sauce",
    ],
    rewardDescription: "รับตั๋วสุ่มฟรี 5 ใบ + คูปองส่วนลด 25%",
    rewardType: "coupon",
    rewardCoupon: {
      id: "coupon_set_combo_25",
      name: "คูปองคอมโบเซ็ต ลด 25%",
      nameEn: "Combo Set 25% Off",
      description: "ลด 25% สำหรับทุกเมนู",
      descriptionEn: "25% discount on all orders",
      rarity: 4,
      type: "discount_percent",
      discountPercent: 25,
      code: "COMBOSET25",
      image: "/meal/longan_juice.jpg",
    },
    rewardTickets: 5,
    badgeTitle: "✨ ผู้เชี่ยวชาญการกิน",
  },
];

// ── 📊 DROP RATES & PROBABILITIES ──
export const GACHA_RATES = {
  UR: 0.02, // 2.0%
  SSR: 0.08, // 8.0%
  SR: 0.25, // 25.0%
  R: 0.65, // 65.0%
};
